#!/usr/bin/ruby
gem "toml-rb"
require "toml"
require "json"
bits, merger = {}, proc { |key, v1, v2| Hash === v1 && Hash === v2 ? v1.merge(v2, &merger) : v2 }
Dir['**/*'].each do |f|
	if File.executable?(f) \
			and not File.directory?(f) \
			and f.include?("/") # in a subdirectory
		bits.merge!(TOML.parse(`./#{f}`), &merger) #rescue nil
	end
end
puts JSON.dump(bits)